### ISSUE TITLE
Ask permission again

### ISSUE THREAD

**Issue by jaydeep17** [tbruyelle/RxPermissions#44]
Once the user denies permission, re-asking it doesn't show up the dialog to allow or deny.
I need to restart the application to make it appear again.

Is it by design? Or I'm missing something ?

``` java
RxPermissions.getInstance(context)
    .request(Manifest.permission.ACCESS_FINE_LOCATION)
    .subscribe(..)
```

**Comment by tbruyelle** [comment]
No of course it's not by design ^^, it's a bug, probably duplicate with #42.

**Comment by artesa** [comment]
@jaydeep17 Sounds interesting. Could you please provide more detailed steps which you can reproduce it with? (Does not happen for me when using both `request()` and `ensure()`).

**Comment by tbruyelle** [comment]
Deployed a new version 0.7.0 that should fix that. Please check.

**Comment by jaydeep17** [comment]
I tried the new version, but it's still the same, it doesn't show up the second time

**Comment by tbruyelle** [comment]
Can you post more code ? I need to understand where and when the library is invoked.

**Comment by jaydeep17** [comment]
Here's a very simplified form of the calls to RxPermissions I have

```java
RxPermissions.getInstance(this)
        .request(Manifest.permission.ACCESS_FINE_LOCATION)
        .flatMap(granted -> RxPermissions.getInstance(this)
            .request(Manifest.permission.ACCESS_FINE_LOCATION))
        .subscribe(...);
```

I don't have it exactly the same way as shown here, the second call to `request` is deep down in a sub function.

**Comment by tbruyelle** [comment]
Why do you need a second call for the same permission ?

**Comment by jaydeep17** [comment]
We have this utility class called RxGoogleMaps that carries out specific operations on Google Maps and every method inside that class that requires location permission asks for the permission before carrying out the operation. For example, `showMyLocationButton()`, `moveToLastKnownLocation()`, etc.
Unfortunately, once the permission is asked, then 2 levels deep we have a `.flatMap()`, that calls another of these RxGoogleMaps method, and thus permission is requested again.

**Comment by tbruyelle** [comment]
I think you should request the permission only one time.

**Comment by jaydeep17** [comment]
True that's a problem on my side, but don't you think RxPermissions should work, even if I request it twice.

**Comment by tbruyelle** [comment]
Yes but it may be not possible since RxPermission had to deal first with configuration changes.

**Comment by BruceeWang** [comment]
I have the same the question for that. If I want to deny this permission again. How can I get to change this permission?

**Comment by tbruyelle** [comment]
> If I want to deny this permission again

Its up to the user to grant or deny, you have no control on that.

**Comment by BruceeWang** [comment]
I mean that when I request the permission again. If the user have granted the permission. the dialog(Permission) is not appear .How can I get the dialog appear again?
(English is not very well,please excuse me)

**Comment by tarasantoshchuk** [comment]
@BruceeWang 

> If the user have granted the permission. the dialog(Permission) is not appear .How can I get the dialog appear again?

After the user have granted the permission, the only way for user to revoke permission is via App Settings. Otherwise dialog won't appear again.

**Comment by ngoctranfire** [comment]
Yea, I actually think this is by design. After the dialog has appeared once, if the user granted or denied the permission, the permission, in theory should not appear again.

**Comment by vekexasia** [comment]
Just to know if there is a way to trigger the dialog ot show again.

**Comment by ngoctranfire** [comment]
Yes, you can clear your data and that should allow you to receive the dialog again.

**Comment by vekexasia** [comment]
Any chance for that to be done programmatically? So that i cant ask
permission till that gets granted?

Il 09 set 2016 6:35 PM, "Ngoc Buu Tran" <notifications@github.com> ha
scritto:

**Comment by toidv** [comment]
Any update on this issue, I have the same issue here. Firstly, I request CAMERA permission (`Manifest.permission.CAMERA`). If user grant the permissionI then request WRITE_STORAGE permission (`Manifest.permission.WRITE_EXTERNAL_STORAGE`). Depending on User grant/decline WRITE_EXTERNAL_STORAGE permission the captured Image will be located at ExternalStorageDirectory/ExternalFilesDir but the request for `WRITE_EXTERNAL_STORAGE` never get callback (`onNext, onError, onComplete`)

**Comment by tarasantoshchuk** [comment]
@toidv 
can you post some code?

**Comment by toidv** [comment]
This is demonstration code @tarasantoshchuk 
Firstly, request camera permission
```
private void requestCameraPermission() {
		mSubscription = rxPermissions.request(Manifest.permission.CAMERA)
					.subscribe(new Subscriber<Boolean>() {
						@Override
						public void onCompleted() {
						}

						@Override
						public void onError(Throwable e) {
							e.printStackTrace();
						}

						@Override
						public void onNext(Boolean aBoolean) {
							if (aBoolean) {
								 requestWriteExternalStoragePermission(MEDIA_TYPE_IMAGE.getMediaType());
							} else {
								InploiUtils.showSnackbar(view, R.string.permissions_not_granted);
							}
						}
					});
	}
```

Then request write external storage permission
```
private void requestWriteExternalStoragePermission(final String mediaTpe) {
        if(mSubscription != null) {
            mSubscription.unsubscribe();
        }
        mSubscription = rxPermissions.request(Manifest.permission.WRITE_EXTERNAL_STORAGE)
                .subscribe(new Subscriber<Boolean>() {
                    @Override
                    public void onCompleted() {
                        Timber.e("onCompleted");
                    }

                    @Override
                    public void onError(Throwable e) {
                        Timber.e("onCompleted");
                        e.printStackTrace();
                    }

                    @Override
                    public void onNext(Boolean aBoolean) {
                        if (!aBoolean) {
                            showSnackbarWarning(aBoolean, mediaTpe);
                        } else {
                            showMediaType(aBoolean, mediaTpe);
                        }
                    }
                });
    }
```

**Comment by arekolek** [comment]
> Why do you need a second call for the same permission ?

Because Android API allows this https://developer.android.com/reference/androidx/core/app/ActivityCompat#requestPermissions(android.app.Activity,%20java.lang.String%5B%5D,%20int)

> Calling this API for permissions already granted to your app would show UI to the user to decided whether the app can still hold these permissions. This can be useful if the way your app uses the data guarded by the permissions changes significantly.

So this looks like a limitation of this library. I'm using 0.10.2 and it still seems not possible to have this?
